substitutions:
  _REGION: 'us-central1'


steps:

# gcloud workflows deploy MY_WORKFLOW \
#    --source=MY_WORKFLOW.YAML \
#    --service-account=MY_SERVICE_ACCOUNT@MY_PROJECT.IAM.GSERVICEACCOUNT.COM

- id: Deploy workflow_parse_lists
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - workflows
  - deploy
  - workflow_parse_lists
  - --source=./workflow_parse_lists/workflow_parse_lists.yaml
  - --location=${_REGION}


- id: Deploy function_data_ingestion
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_data_ingestion
  - --region=${_REGION}
  - --source=./function_data_ingestion/
  - --trigger-bucket=tournament-lists
  - --runtime=python39

# - id: Deploy function-data-conversion
#   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#   - gcloud
#   - functions
#   - deploy
#   - FUNCTION_NAME
#   - --region=${_REGION}
#   - --source=.
#   - --trigger-http
#   - --runtime=python39