substitutions:
  _REGION: 'us-central1'


steps:

- id: Deploy workflow_parse_lists
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - workflows
  - deploy
  - workflow_parse_lists
  - --source=./workflow_parse_lists/workflow_parse_lists.yaml
  - --location=${_REGION}
  waitFor: ['-']


- id: Deploy function_data_ingestion
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_data_ingestion
  - --region=${_REGION}
  - --source=./function_data_ingestion/
  - --trigger-bucket=tournament-lists
  - --runtime=python39
  waitFor: ['-']

- id: Deploy function-data-conversion
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_data_conversion
  - --region=${_REGION}
  - --source=./function_data_conversion/
  - --trigger-http
  - --runtime=python39
  waitFor: ['-']