substitutions:
  _REGION: "us-central1"

steps:
  - id: Deploy function-data-conversion
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - function-data-conversion
      - --region=${_REGION}
      - --source=./function_data_conversion/
      - --entry-point=function_data_conversion
      - --trigger-http
      - --runtime=python39
      - --timeout=1800
      - --gen2
      - --set-secret=NR_CREDENTIALS_SECRET=NR_PASSWORD:latest

# metadata:
#   permission: artifactregistry.repositories.update
#   resource: projects/ninthage-data-analytics/locations/us-central1/repositories/gcf-artifacts
# reason: IAM_PERMISSION_DENIED
  # - id: ensure delete policy is enabled
  #   name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   args:
  #     - gcloud
  #     - artifacts
  #     - repositories
  #     - set-cleanup-policies
  #     - gcf-artifacts
  #     - --project=ninthage-data-analytics
  #     - --location=us-central1
  #     - --policy=function_data_conversion/artifact-registry-delete-policy.json
