substitutions:
  _REGION: "us-central1"

steps:
  - id: Deploy function-data-conversion
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - function-data-conversion
      - --region=${_REGION}
      - --source=./function_data_conversion/
      - --entry-point=function_data_conversion
      - --trigger-http
      - --runtime=python39
      - --timeout=1800
      - --gen2
