substitutions:
  _REGION: "us-central1"

steps:
  - id: Deploy function-data-conversion
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - function-data-conversion
      - --region=${_REGION}
      - --source=./function_data_conversion/
      - --entry-point=function_data_conversion
      - --trigger-http
      - --runtime=python39
      - --timeout=1800
      - --gen2

  - id: ensure delete policy is enabled
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - artifacts
      - repositories
      - set-cleanup-policies
      - gcf-artifacts
      - --project=ninthage-data-analytics
      - --location=us-central1
      - --policy=function_data_conversion/artifact-registry-delete-policy.json