substitutions:
  _REGION: 'us-central1'


steps:

- id: Deploy function_new_recruit_tournaments
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
      - gcloud
      - functions
      - deploy
      - function_new_recruit_tournaments
      - --region=${_REGION}
      - --source=.
      - --trigger-http
      - --timeout=300
      - --runtime=python312
      - --gen2
      - --memory=1024MB
      - --docker-registry=artifact-registry
      - --set-secrets=NR_CREDENTIALS_SECRET=projects/${PROJECT_ID}/secrets/NR_CREDENTIALS/versions/latest
      - --set-secrets=PROXY=projects/${PROJECT_ID}/secrets/HTTP_PROXY/versions/latest
