substitutions:
  _REGION: 'us-central1'

steps:

- id: Deploy function_new_recruit_tournaments
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
      - gcloud
      - beta
      - functions
      - deploy
      - function_new_recruit_tournaments
      - --region=${_REGION}
      - --source=./function_new_recruit_tournaments/
      - --trigger-http
      - --timeout=300
      - --runtime=python39
      - --memory=1024MB
      - --docker-registry=artifact-registry
      - --set-secrets=NR_CREDENTIALS_SECRET=NR_CREDENTIALS:latest
