substitutions:
  _REGION: 'us-central1'


steps:

- id: Deploy function_new_recruit_torunaments
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
      - gcloud
      - beta
      - functions
      - deploy
      - function_new_recruit_torunaments
      - --region=${_REGION}
      - --source=./function_new_recruit_torunaments/
      - --trigger-http
      - --runtime=python39
