substitutions:
  _REGION: 'us-central1'


steps:

- id: Deploy function_discord_error_reporting
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - beta
  - functions
  - deploy
  - function_discord_error_reporting
  - --region=${_REGION}
  - --source=./function_discord_error_reporting/
  - --trigger-http
  - --runtime=python39
  - --set-secrets "DISCORD_WEBHOOK_TOKEN=DISCORD_WEBHOOK_TOKEN:latest,DISCORD_WEBHOOK_ID=DISCORD_WEBHOOK_ID:latest"
