substitutions:
  _REGION: 'us-central1'


steps:

- id: Deploy function_discord_success_reporting
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_discord_success_reporting
  - --region=${_REGION}
  - --source=./function_discord_success_reporting/
  - --trigger-http
  - --runtime=python312
  - --gen2
  - --update-secrets=DISCORD_WEBHOOK_TOKEN=DISCORD_WEBHOOK_TOKEN:latest
  - --update-secrets=DISCORD_WEBHOOK_ID=DISCORD_WEBHOOK_ID:latest
