substitutions:
  _REGION: 'us-central1'


steps:

- id: Deploy function_data_ingestion
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_data_ingestion
  - --region=${_REGION}
  - --source=.
  - --trigger-event-filters=type=google.cloud.storage.object.v1.finalized
  - --trigger-event-filters=bucket=tournament-lists
  - --runtime=python312
  - --gen2
