substitutions:
  _REGION: 'us-central1'


steps:

- id: Deploy function_fading_flame
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
      - gcloud
      - functions
      - deploy
      - function_game_report
      - --region=${_REGION}
      - --source=./function_fading_flame/
      - --trigger-http
      - --runtime=python39
