substitutions:
  _REGION: 'us-west1'


steps:

- id: Deploy function_upload_data_into_bigquery
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_upload_data_into_bigquery
  - --region=${_REGION}
  - --source=./function_upload_data_into_bigquery/
  - --trigger-http
  - --runtime=python39
